### ISSUE TITLE
DVR integration

### ISSUE THREAD

**Issue by mastroantonio** [mezz64/pyHik#26]
I believe the error is related to the server's response
http://xxx.xxx.x.xxx/ISAPI/System/deviceInfo.
I am attaching a screen of the answer.
The deviceType entry is DVR

![isapi](https://user-images.githubusercontent.com/44971248/48706033-3eef7800-ebfb-11e8-87c9-20927c60d940.JPG)

**Comment by mezz64** [comment]
Please add debug logging lines to your hass config for pyhik and post the output from a HASS start when you have the DVR configured.  

```
logs:
   pyhik.hikvision: debug
   homeassistant.components.binary_sensor.hikvision: debug
```

I don't perform any setup based on the deviceType field so that alone shouldn't be preventing things from working.  While you're at it post the output of your triggers endpoint and verify you get a continuously downloading file when you try to go to the alertStream url in a browser.  Unfortunately, many of these devices have only a partial API and the alertStream is left out.

**Comment by mezz64** [comment]
I'm afraid I don't have any api documentation on what type of stream the "alarm center" reports.  If you can find some documentation and/or provide a sample from the stream showing some events being triggered I can look into adding it as an option.

**Comment by madprunes** [comment]
I had a similar problem initially with my DVR/NVR there was no alertStream, updating to the latest USA firmware (as the others were still too old) gave me the alertStream.

As far as alarm host goes, that is a HTTP server which the NVR/DVR posts it's event messages to, I believe that is what it is explaining on page 344 of the HIKVISION ISAPI_2.6-IPMD Service.pdf document.
